### ISSUE TITLE
How to use in an environment variable in values?

### ISSUE THREAD

**Issue by radist** [neuroforgede/nothelm.py#6]
sample

In .gitlab-ci.yml  set
```
GITLAB_NAMESPACE: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG
```
In values.yaml use

```
postgresql_volume_config: 
  driver: local-persist
  driver_opts:
    mountpoint: /data/{{ gitlab_namespace }}-postgresql/
```
